apiVersion: v1
kind: ServiceAccount
metadata:
  name: delete-interceptor
  namespace: webhook-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-interceptor-rollback
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - patch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-interceptor-rollback
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: delete-interceptor-rollback
subjects:
  - kind: ServiceAccount
    name: delete-interceptor
    namespace: webhook-system
