apiVersion: v1
kind: Service
metadata:
  name: delete-interceptor-svc
  namespace: webhook-system
  labels:
    app.kubernetes.io/name: delete-interceptor
spec:
  selector:
    app.kubernetes.io/name: delete-interceptor
  ports:
    - name: https
      port: 443
      targetPort: https
